# Copyright 2019 Smarter Grid Solutions
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Main implementation package for the device simulator."""

import os
import sys
import warnings

self_dir = os.path.dirname(__file__)
import_dir = os.path.abspath(os.path.join(self_dir, "..", "deps",
                                          "openfmb", "openfmb"))
sys.path.append(import_dir)
sys.path.append(os.path.join(import_dir, "breakermodule"))
sys.path.append(os.path.join(import_dir, "commonmodule"))
sys.path.append(os.path.join(import_dir, "generationmodule"))
sys.path.append(os.path.join(import_dir, "metermodule"))
sys.path.append(os.path.join(import_dir, "reclosermodule"))
sys.path.append(os.path.join(import_dir, "solarmodule"))

# These are generated by protobuf and jinja2, so we don't want to see that here
warnings.filterwarnings("ignore",
                        category=DeprecationWarning,
                        module="google.protobuf")
warnings.filterwarnings("ignore",
                        category=DeprecationWarning,
                        module="jinja2")
